### PR TITLE
18: Edison Sensor Web Demo

### PR DESCRIPTION
**Pull request by keilw**
Task-Url: https://github.com/unitsofmeasurement/uom-demos/issues/issues/18
Using this Sensor Web Demo to track the PR.

Renamed typo in SensorRepPository and fixed a compile problem with current Diana API.
Please advise, what to use in place of cast()?

### CODE REVIEW

**Comment by otaviojava** [comment]
Thanks @keilw

**Comment by keilw** [comment]
I will try it, is it supposed to work with the new API (no cast() method)?

**Comment by otaviojava** [comment]
yes

**Comment by keilw** [comment]
I'll try, see the TODO, it seems cast() automatically returned a list of strings, this no longer worked, so only a single string is returned in a list now, hope that's OK?

**Pull request merged**
